id: P006835
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG14746
  title: པདྨ་འོད་འབར་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    d2ce671ba8b649bf83ec032725e79eb0:
      image_group_id: I2PD18173
      title: ''
      volume_number: 1
      total_pages: 172
      base_file: v001.txt
